import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;`);
await db.exec(readFileSync('supabase/migrations/202609230001_invoice_studio.sql','utf8'));
console.log('PASS migration applies');
const a='00000000-0000-4000-8000-000000000001',b='00000000-0000-4000-8000-000000000002';
await db.exec(`insert into auth.users values('${a}'),('${b}');`);
async function asUser(id){await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);}
async function call(name,args=[],placeholders=args.map((_,i)=>'$'+(i+1)).join(',')){return (await db.query(`select public.${name}(${placeholders}) as result`,args)).rows[0].result;}
await asUser(a);
assert.equal((await call('studio_workspace')).invoices.length,0);
const party={name:'Test business',address:'Vilnius 1',country_code:'LT'};
const profile={details:party,default_currency:'EUR',default_payment_terms_days:14,default_notes:'Thanks'};
await call('studio_save_profile',[profile]);
const customer=await call('studio_save_customer',[{name:'Test customer',details:{address:'Kaunas 1',country_code:'LT'}}]);
const payload={id:'00000000-0000-4000-8000-000000000003',customer_id:customer.id,type:'standard',issue_date:'2026-01-02',due_date:'2026-01-16',service_date:null,payment_terms_days:14,currency:'EUR',seller_snapshot:party,customer_snapshot:party,notes:'Test',items:[{description:'Service',quantity:'2',unit_price:'50',tax_rate:'21'}]};
let invoice=await call('studio_save_draft',[payload]);assert.equal(Number(invoice.total),121);
invoice=await call('studio_invoice_action',[invoice.id,'issue',{}]);assert.equal(invoice.number,'INV-2026-000001');
assert.equal((await call('studio_invoice_action',[invoice.id,'issue',{}])).number,invoice.number);
await assert.rejects(()=>call('studio_save_draft',[payload]),/Only drafts/);
await call('studio_invoice_action',[invoice.id,'pay',{paid_on:'2026-01-03'}]);
await assert.rejects(()=>call('studio_invoice_action',[invoice.id,'cancel',{reason:'Test'}]),/Only an issued/);
await call('studio_invoice_action',[invoice.id,'unpay',{}]);
await assert.rejects(()=>call('studio_invoice_action',[invoice.id,'cancel',{reason:''}]),/reason/);
await call('studio_invoice_action',[invoice.id,'cancel',{reason:'Replaced'}]);
const copy=await call('studio_invoice_action',[invoice.id,'duplicate',{}]);assert.equal(copy.status,'draft');assert.equal(copy.number,null);assert.equal(copy.paid_on,null);assert.equal(copy.cancellation_reason,null);assert.equal(Number(copy.total),121);
await asUser(b);assert.equal((await call('studio_workspace')).invoices.length,0);
await assert.rejects(()=>call('studio_invoice_action',[invoice.id,'duplicate',{}]),/not found/);
await assert.rejects(()=>call('studio_save_draft',[{...payload,id:crypto.randomUUID()}]),/foreign key/);
await assert.rejects(()=>call('studio_save_customer',[{...customer,name:'Hijack'}]),/not found/);
await db.exec('set role authenticated');
await assert.rejects(()=>db.query('select * from invoice_studio.invoices'),/permission denied/);
assert.equal((await call('studio_workspace')).invoices.length,0);
await db.exec('reset role');await asUser('');
await assert.rejects(()=>call('studio_workspace'),/Sign in/);
console.log('PASS totals, issue idempotency, immutability, statuses, duplication, ownership and direct-table isolation');
await db.close();
