import assert from 'node:assert/strict';
import { totals, newInvoice, duplicateInvoice, validateIssue, emptyProfile, today, addDays } from '../lib/invoice.ts';
assert.equal(totals([{ description: 'Service', quantity: 2, unit_price: 50, tax_rate: 21 }]).total, '121.00');
assert.equal(totals([{ description: 'Rounding', quantity: 1, unit_price: '1.005', tax_rate: 0 }]).total, '1.01');
assert.equal(totals([{ description: 'Tax rounding', quantity: 1, unit_price: '0.05', tax_rate: 10 }]).tax_total, '0.01');
assert.equal(totals([{ description: 'Fraction', quantity: '0.3333', unit_price: '100', tax_rate: 21 }]).total, '40.33');
assert.throws(() => totals([{ description: 'Invalid', quantity: -1, unit_price: 50, tax_rate: 0 }]));
const profile = { ...emptyProfile, details: { name: 'Žilvinas Studio', address: 'Vilnius', country_code: 'LT' } };
const i = { ...newInvoice(profile), status: 'paid' as const, number: 'INV-2026-000001', paid_on: today(), customer_snapshot: profile.details, ...totals([{ description: 'Design', quantity: 1, unit_price: 50, tax_rate: 0 }]) };
validateIssue(i);
const copy = duplicateInvoice(i, profile);
assert.notEqual(copy.id, i.id);
assert.equal(copy.number, null);
assert.equal(copy.status, 'draft');
assert.equal(copy.paid_on, null);
assert.equal(copy.issue_date, today());
assert.equal(copy.due_date, addDays(today(), 14));
assert.equal(copy.total, '50.00');
assert.equal(i.number, 'INV-2026-000001');
assert.equal(copy.service_date, null);
console.log('PASS decimal rounding, validation and duplication reset rules');
